# https://medium.com/@skunkworker/rails-5-1-system-tests-on-travis-ci-5b03cbc9014d
language: ruby
rvm:
  - 2.3.3
services:
  - postgresql
env: 
  - RAILS_ENV=test
before_script:
  - cp ./.travis.database.yml ./config/database.yml
  - travis_retry yarn install
  - RAILS_ENV=test bin/rails webpacker:compile
  - wget http://chromedriver.storage.googleapis.com/2.34/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo apt-get install libnss3
  - sudo apt-get --only-upgrade install google-chrome-stable
  - sudo cp chromedriver /usr/local/bin/.
  - sudo chmod +x /usr/local/bin/chromedriver
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
sudo: required
addons:
  sources:
  - google-chrome
  apt:
    packages:
    - google-chrome-stable
script:
  - bin/rails db:create 
  - bin/rails db:migrate
  - bin/rspec
  - bin/rspec spec/system/*