language: ruby
rvm:
  - 2.3.1
services:
  - postgresql
env: 
  - RAILS_ENV=test
before_script:
  - cp ./.travis.database.yml ./config/database.yml
script:
  - bin/rails db:create 
  - bin/rails db:migrate
  - bin/rspec
  - bin/rspec spec/system/*