language: ruby
rvm:
  - 2.3.1
services:
  - postgresql
env: 
  - RAILS_ENV=test
before_script:
  - "cp ./.travis.database.yml ./config/database.yml"
  - psql -c 'create database mundialApp_test' -U postgres
script:
  - bin/rails db:migrate
  - bin/rspec