FROM ruby:2.5
LABEL maintainer="Wojciech Mikusek"
RUN apt-get update && apt-get install apt-transport-https
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs yarn
RUN mkdir /typer
WORKDIR /typer
ADD Gemfile /typer/Gemfile
ADD Gemfile.lock /typer/Gemfile.lock
RUN bundle install
ADD . /typer
RUN yarn cache clean
RUN yarn install
