User.find_or_initialize_by(login: 'admin').update(first_name: 'Jan', last_name: 'Kowalski', email: 'admin@example.com', password: 'password', password_confirmation: 'password', admin: true)

pl = Team.find_or_initialize_by(name: "Polska", flag: "pl")
ru = Team.find_or_initialize_by(name: "Rosja", flag: "ru")
fr = Team.find_or_initialize_by(name: "Francja", flag: "fr")
pt = Team.find_or_initialize_by(name: "Portugalia", flag: "pt")
de = Team.find_or_initialize_by(name: "Niemcy", flag: "de")
rs = Team.find_or_initialize_by(name: "Serbia", flag: "rs")
Team.find_or_initialize_by(name: "Anglia", flag: "gb")
Team.find_or_initialize_by(name: "Hiszpania", flag: "es")
Team.find_or_initialize_by(name: "Belgia", flag: "be")
Team.find_or_initialize_by(name: "Islandia", flag: "is")
Team.find_or_initialize_by(name: "Szwajcaria", flag: "ch")
Team.find_or_initialize_by(name: "Chorwacja", flag: "hr")
Team.find_or_initialize_by(name: "Dania", flag: "dk")
Team.find_or_initialize_by(name: "Szwecja", flag: "se")
Team.find_or_initialize_by(name: "Tunezja", flag: "tn")
Team.find_or_initialize_by(name: "Nigeria", flag: "ng")
Team.find_or_initialize_by(name: "Maroko", flag: "ma")
Team.find_or_initialize_by(name: "Senegal", flag: "sn")
Team.find_or_initialize_by(name: "Egipt", flag: "eg")
Team.find_or_initialize_by(name: "Iran", flag: "ir")
Team.find_or_initialize_by(name: "Japonia", flag: "jp")
Team.find_or_initialize_by(name: "Korea Płd", flag: "kr")
Team.find_or_initialize_by(name: "Arabia Saudyjska", flag: "sa")
Team.find_or_initialize_by(name: "Brazylia", flag: "br")
Team.find_or_initialize_by(name: "Urugwaj", flag: "uy")
Team.find_or_initialize_by(name: "Argentyna", flag: "ar")
Team.find_or_initialize_by(name: "Kolumbia", flag: "co")
Team.find_or_initialize_by(name: "Meksyk", flag: "mx")
cr = Team.find_or_initialize_by(name: "Kostaryka", flag: "cr")
pa = Team.find_or_initialize_by(name: "Panama", flag: "pa")
au = Team.find_or_initialize_by(name: "Australia", flag: "au")
pe = Team.find_or_initialize_by(name: "Peru", flag: "pe")

r1 = Round.find_or_initialize_by(title: "Faza grupowa 1")
r1.update(score_factor: 1)
r2 = Round.find_or_initialize_by(title: "Faza grupowa 2")
r2.update(score_factor: 1)
Round.find_or_initialize_by(title: "Faza grupowa 3").update(score_factor: 1)
Round.find_or_initialize_by(title: "1/8 finału").update(score_factor: 1)
Round.find_or_initialize_by(title: "Ćwierćfinały").update(score_factor: 1)
Round.find_or_initialize_by(title: "Półfinały").update(score_factor: 1)
Round.find_or_initialize_by(title: "Finał").update(score_factor: 1)

r1md1 = MatchDay.find_or_initialize_by(day_number: 1)
r1md1.update(stop_bet_time: DateTime.new(2018,6,11,18,0,0,"+1"), round: r1)
r1md1.matches.delete_all
r1md1.matches.create(city: "Moskwa", start_time: DateTime.new(2018,6,11,19,0,0,"+1"), team1: pl, team2: cr)
r1md1.matches.create(city: "Petersburg", start_time: DateTime.new(2018,6,11,22,0,0,"+1"), team1: au, team2: pt)

r1md2 = MatchDay.find_or_initialize_by(day_number: 2)
r1md2.update(stop_bet_time: DateTime.new(2018,6,12,18,0,0,"+1"), round: r1)
r1md2.matches.delete_all
r1md2.matches.create(city: "Moskwa", start_time: DateTime.new(2018,6,12,19,0,0,"+1"), team1: de, team2: ru)
r1md2.matches.create(city: "Petersburg", start_time: DateTime.new(2018,6,12,22,0,0,"+1"), team1: rs, team2: pt)

r2md3 = MatchDay.find_or_initialize_by(day_number: 3)
r2md3.update(stop_bet_time: DateTime.new(2018,6,14,18,0,0,"+1"), round: r2)
r2md3.matches.delete_all
r2md3.matches.create(city: "Nowosybirsk", start_time: DateTime.new(2018,6,14,19,0,0,"+1"), team1: pl, team2: ru)
r2md3.matches.create(city: "Nowogród", start_time: DateTime.new(2018,6,14,22,0,0,"+1"), team1: fr, team2: pt)

r2md4 = MatchDay.find_or_initialize_by(day_number: 4)
r2md4.update(stop_bet_time: DateTime.new(2018,6,15,18,0,0,"+1"), round: r2)
r2md4.matches.delete_all
r2md4.matches.create(city: "Nowosybirsk", start_time: DateTime.new(2018,6,14,19,0,0,"+1"), team1: au, team2: pe)
r2md4.matches.create(city: "Nowogród", start_time: DateTime.new(2018,6,14,22,0,0,"+1"), team1: cr, team2: pa)

