User.find_or_initialize_by(login: 'admin').update(first_name: 'Jan', last_name: 'Kowalski', email: 'admin@example.com', password: 'password', password_confirmation: 'password', admin: true)

pl = Team.find_or_initialize_by(name: "Polska", flag: "pl")
ru = Team.find_or_initialize_by(name: "Rosja", flag: "ru")
fr = Team.find_or_initialize_by(name: "Francja", flag: "fr")
pt = Team.find_or_initialize_by(name: "Portugalia", flag: "pt")
de = Team.find_or_initialize_by(name: "Niemcy", flag: "de")
rs = Team.find_or_initialize_by(name: "Serbia", flag: "rs")
gb = Team.find_or_initialize_by(name: "Anglia", flag: "gb")
es = Team.find_or_initialize_by(name: "Hiszpania", flag: "es")
be = Team.find_or_initialize_by(name: "Belgia", flag: "be")
is = Team.find_or_initialize_by(name: "Islandia", flag: "is")
ch = Team.find_or_initialize_by(name: "Szwajcaria", flag: "ch")
hr = Team.find_or_initialize_by(name: "Chorwacja", flag: "hr")
dk = Team.find_or_initialize_by(name: "Dania", flag: "dk")
se = Team.find_or_initialize_by(name: "Szwecja", flag: "se")
tn = Team.find_or_initialize_by(name: "Tunezja", flag: "tn")
ng = Team.find_or_initialize_by(name: "Nigeria", flag: "ng")
ma = Team.find_or_initialize_by(name: "Maroko", flag: "ma")
sn = Team.find_or_initialize_by(name: "Senegal", flag: "sn")
eg = Team.find_or_initialize_by(name: "Egipt", flag: "eg")
ir = Team.find_or_initialize_by(name: "Iran", flag: "ir")
jp = Team.find_or_initialize_by(name: "Japonia", flag: "jp")
kr = Team.find_or_initialize_by(name: "Korea Płd", flag: "kr")
sa = Team.find_or_initialize_by(name: "Arabia Saudyjska", flag: "sa")
br = Team.find_or_initialize_by(name: "Brazylia", flag: "br")
uy = Team.find_or_initialize_by(name: "Urugwaj", flag: "uy")
ar = Team.find_or_initialize_by(name: "Argentyna", flag: "ar")
co = Team.find_or_initialize_by(name: "Kolumbia", flag: "co")
mx = Team.find_or_initialize_by(name: "Meksyk", flag: "mx")
cr = Team.find_or_initialize_by(name: "Kostaryka", flag: "cr")
pa = Team.find_or_initialize_by(name: "Panama", flag: "pa")
au = Team.find_or_initialize_by(name: "Australia", flag: "au")
pe = Team.find_or_initialize_by(name: "Peru", flag: "pe")

r1 = Round.find_or_initialize_by(title: "Faza grupowa 1")
r2 = Round.find_or_initialize_by(title: "Faza grupowa 2")
r3 = Round.find_or_initialize_by(title: "Faza grupowa 3")
r4 = Round.find_or_initialize_by(title: "1/8 finału")
r5 = Round.find_or_initialize_by(title: "Ćwierćfinały")
r6 = Round.find_or_initialize_by(title: "Półfinały")
r7 = Round.find_or_initialize_by(title: "Finał")

md1 = MatchDay.find_or_initialize_by(day_number: 1)
md1.update(stop_bet_time: DateTime.new(2018,6,14,15,0,0,"+2"), round: r1)
md1.matches.delete_all
md1.matches.create(city: "Moskwa", start_time: DateTime.new(2018,6,14,17,0,0,"+2"), team1: ru, team2: sa)

md2 = MatchDay.find_or_initialize_by(day_number: 2)
md2.update(stop_bet_time: DateTime.new(2018,6,15,12,0,0,"+2"), round: r1)
md2.matches.delete_all
md2.matches.create(city: "Jekaterynburg", start_time: DateTime.new(2018,6,15,14,0,0,"+2"), team1: eg, team2: uy)
md2.matches.create(city: "St. Petersburg", start_time: DateTime.new(2018,6,15,17,0,0,"+2"), team1: ma, team2: ir)
md2.matches.create(city: "Soczi", start_time: DateTime.new(2018,6,15,20,0,0,"+2"), team1: pt, team2: es)

md3 = MatchDay.find_or_initialize_by(day_number: 3)
md3.update(stop_bet_time: DateTime.new(2018,6,16,10,0,0,"+2"), round: r1)
md3.matches.delete_all
md3.matches.create(city: "Kazań", start_time: DateTime.new(2018,6,16,12,0,0,"+2"), team1: fr, team2: au)
md3.matches.create(city: "Moskwa", start_time: DateTime.new(2018,6,16,15,0,0,"+2"), team1: ar, team2: is)
md3.matches.create(city: "Sarańsk", start_time: DateTime.new(2018,6,16,18,0,0,"+2"), team1: pe, team2: dk)
md3.matches.create(city: "Kaliningrad", start_time: DateTime.new(2018,6,16,21,0,0,"+2"), team1: hr, team2: ng)

md4 = MatchDay.find_or_initialize_by(day_number: 4)
md4.update(stop_bet_time: DateTime.new(2018,6,17,12,0,0,"+2"), round: r1)
md4.matches.delete_all
md4.matches.create(city: "Samara", start_time: DateTime.new(2018,6,17,14,0,0,"+2"), team1: cr, team2: rs)
md4.matches.create(city: "Moskwa", start_time: DateTime.new(2018,6,17,17,0,0,"+2"), team1: de, team2: mx)
md4.matches.create(city: "Rostów", start_time: DateTime.new(2018,6,17,20,0,0,"+2"), team1: br, team2: ch)

md5 = MatchDay.find_or_initialize_by(day_number: 5)
md5.update(stop_bet_time: DateTime.new(2018,6,18,12,0,0,"+2"), round: r1)
md5.matches.delete_all
md5.matches.create(city: "Niżny Nowogród", start_time: DateTime.new(2018,6,18,14,0,0,"+2"), team1: se, team2: kr)
md5.matches.create(city: "Soczi", start_time: DateTime.new(2018,6,18,17,0,0,"+2"), team1: be, team2: pa)
md5.matches.create(city: "Wołgograd", start_time: DateTime.new(2018,6,18,20,0,0,"+2"), team1: tn, team2: gb)

md6 = MatchDay.find_or_initialize_by(day_number: 6)
md6.update(stop_bet_time: DateTime.new(2018,6,19,12,0,0,"+2"), round: r1)
md6.matches.delete_all
md6.matches.create(city: "Sarańsk", start_time: DateTime.new(2018,6,19,14,0,0,"+2"), team1: co, team2: jp)
md6.matches.create(city: "Moskwa", start_time: DateTime.new(2018,6,19,17,0,0,"+2"), team1: pl, team2: sn)
